version: '2.2'

volumes:
    mariadb-volume:
    glance-images:

services:
    mariadb:
        image: 'mariadb:10.1.22'
        env_file: './config'
        environment:
            MARIADB_EXTRA_FLAGS: '--max-connections=8192'
        hostname: 'mariadb'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes: 
            - 'mariadb-volume:/var/lib/mysql'

    rabbitmq:
        image: 'rabbitmq:3'
        env_file: './config'
        hostname: 'control'
        ports:
            - '5672:5672'
        expose:
            - '5672'

    keystone-api:
        image: 'hogepodge/locistack-keystone:master-centos'
        env_file: './config'
        hostname: 'keystone'
        extra_hosts:
            - "control:192.168.1.32"
        ports:
            - '5000:5000'
            - '35357:35357'
        expose:
            - '5000'
            - '35357'
        links:
            - 'mariadb'
            - 'rabbitmq'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/keystone:/scripts/keystone'
            - './tls:/tls'
        command: '/scripts/keystone/start-keystone-api.sh'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'

    glance-api:
        image: 'hogepodge/locistack-glance:master-centos'
        env_file: './config'
        hostname: 'glance-api'
        extra_hosts:
            - "control:192.168.1.32"
        links:
            - 'mariadb'
            - 'rabbitmq'
        ports:
            - '9292:9292'
        expose:
            - '9292'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/glance:/scripts/glance'
            - './tls:/tls'
            - '/dev/loop0:/dev/loop0'
        command: '/scripts/glance/start-glance-api.sh'

    glance-registry:
        image: 'hogepodge/locistack-glance:master-centos'
        env_file: './config'
        hostname: 'glance-registry'
        extra_hosts:
            - "control:192.168.1.32"
        links:
            - 'mariadb'
            - 'rabbitmq'
        ports:
            - '9191:9191'
        expose:
            - '9191'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
            - 'glance-api'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/glance:/scripts/glance'
            - './tls:/tls'
        command: '/scripts/glance/start-glance-registry.sh'

    neutron-server:
        image: 'hogepodge/locistack-neutron:master-centos'
        env_file: './config'
        hostname: 'neutron-server'
        extra_hosts:
            - "control:192.168.1.32"
        links:
            - 'mariadb'
            - 'rabbitmq'
        ports:
            - '9696:9696'
        expose:
            - '9696'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/neutron:/scripts/neutron'
            - './tls:/tls'
        command: '/scripts/neutron/start-neutron-server.sh'


    neutron-linuxbridge-agent:
        image: 'hogepodge/locistack-neutron:master-centos'
        env_file: './config'
        hostname: 'neutron-linuxbridge-agent'
        privileged: true
        network_mode: 'host'
        cap_add:
            - ALL
        sysctls:
            net.ipv4.conf.all.promote_secondaries: 1
            net.ipv4.ip_forward: 1
            net.ipv4.conf.all.rp_filter: 0
            net.ipv4.conf.default.rp_filter: 0
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
            - 'neutron-server'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/neutron:/scripts/neutron'
            - './tls:/tls'
        command: '/scripts/neutron/start-neutron-linuxbridge-agent.sh'

    neutron-dhcp-agent:
        image: 'hogepodge/locistack-neutron:master-centos'
        env_file: './config'
        hostname: 'neutron-dhcp-agent'
        privileged: true
        network_mode: 'host'
        cap_add:
            - 'ALL'
            - 'NET_ADMIN'
        sysctls:
            net.ipv4.conf.all.promote_secondaries: 1
            net.ipv4.ip_forward: 1
            net.ipv4.conf.all.rp_filter: 0
            net.ipv4.conf.default.rp_filter: 0
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
            - 'neutron-server'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/neutron:/scripts/neutron'
            - './tls:/tls'
        command: '/scripts/neutron/start-neutron-dhcp-agent.sh'

    neutron-metadata-agent:
        image: 'hogepodge/locistack-neutron:master-centos'
        env_file: './config'
        hostname: 'neutron-metadata-agent'
        privileged: true
        network_mode: 'host'
        cap_add:
            - 'NET_ADMIN'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
            - 'neutron-server'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/neutron:/scripts/neutron'
            - './tls:/tls'
        command: '/scripts/neutron/start-neutron-metadata-agent.sh'

    nova-api:
        image: 'hogepodge/locistack-nova:master-centos'
        env_file: './config'
        hostname: 'nova-api'
        extra_hosts:
            - "control:192.168.1.32"
        links:
            - 'mariadb'
            - 'rabbitmq'
        ports:
            - '8774:8774'
        expose:
            - '8774'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/nova:/scripts/nova'
            - './tls:/tls'
        command: '/scripts/nova/start-nova-api.sh'

    nova-metadata:
        image: 'hogepodge/locistack-nova:master-centos'
        env_file: './config'
        hostname: 'nova-api'
        extra_hosts:
            - "control:192.168.1.32"
        links:
            - 'mariadb'
            - 'rabbitmq'
        ports:
            - '8775:8775'
        expose:
            - '8775'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/nova:/scripts/nova'
            - './tls:/tls'
        command: '/scripts/nova/start-nova-api.sh'

    nova-placement:
        image: 'hogepodge/locistack-nova:master-centos'
        env_file: './config'
        hostname: 'nova-placement'
        extra_hosts:
            - "control:192.168.1.32"
        links:
            - 'mariadb'
            - 'rabbitmq'
        ports:
            - '8778:8000'
        expose:
            - '8000'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
            - 'nova-api'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/nova:/scripts/nova'
            - './tls:/tls'
        command: '/scripts/nova/start-nova-placement.sh'

    nova-conductor:
        image: 'hogepodge/locistack-nova:master-centos'
        env_file: './config'
        hostname: 'nova-conductor'
        extra_hosts:
            - "control:192.168.1.32"
        links:
            - 'mariadb'
            - 'rabbitmq'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
            - 'nova-api'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/nova:/scripts/nova'
            - './tls:/tls'
        command: '/scripts/nova/start-nova-conductor.sh'

    nova-scheduler:
        image: 'hogepodge/locistack-nova:master-centos'
        env_file: './config'
        hostname: 'nova-scheduler'
        extra_hosts:
            - "control:192.168.1.32"
        links:
            - 'mariadb'
            - 'rabbitmq'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
            - 'nova-api'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/nova:/scripts/nova'
            - './tls:/tls'
        command: '/scripts/nova/start-nova-scheduler.sh'

    libvirt:
        image: 'hogepodge/locistack-libvirt:master-centos'
        privileged: 'true'
        network_mode: 'host'
        pid: 'host'
        ipc: 'host'
        user: 'root'
        volumes:
            - '/:/host'
            - '/sys:/host-sys'
            - '/dev:/host-dev'
            - '/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket'
            - '/var/run/libvirt:/var/run/libvirt'
        command: '/start-libvirt.sh'

    nova-compute:
        image: 'hogepodge/locistack-nova:master-centos'
        env_file: './config'
        hostname: 'nova-compute'
        extra_hosts:
            - "control:192.168.1.32"
        links:
            - 'mariadb'
            - 'rabbitmq'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/nova:/scripts/nova'
            - './tls:/tls'
            - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
            - /var/run/libvirt:/var/run/libvirt 
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
            - 'nova-api'
        command: '/scripts/nova/start-nova-compute.sh'

